image:https://travis-ci.org/spidermonkey/dbmonitor.svg?branch=master["Build Status", link="https://travis-ci.org/spidermonkey/dbmonitor"]

= Database monitoring application

== Building from Source
The application can be easily built with the
https://github.com/takari/maven-wrapper[maven wrapper]. You also need JDK 1.8.

[indent=0]
----
	$ ./mvnw clean install
----

If you want to build with the regular `mvn` command, you will need
http://maven.apache.org/run-maven/index.html[Maven v3.2.1 or above].

NOTE: You may need to increase the amount of memory available to Maven by setting
a `MAVEN_OPTS` environment variable with the value `-Xmx512m`.

NOTE: To compile/work with the code in your IDE you most probably need to install Lombok plugin.

== Starting the application
To start the aplication use 
https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/maven-plugin/[Spring Boot Maven Plugin]

[indent=0]
----
	$ ./mvnw clean spring-boot:run
----

The regular `mvn` command can also be used.The application starts up on port number: `8080`.
Use `-Dserver.port=<alternative port>` option to set alternative port number.

 

== How to use the application

==== The main application

The main application is available on the root (`/`) context-path. i.e: http://localhost:8080/

==== Interaction with the database

To interact with the The http://www.h2database.com/html/main.html[H2 database]: console is exposed in `/console/`. In case of using default port: http://localhost:8080/console/

IMPORTANT: Please use the following connection details to log in to the database:

[indent=0]
----
    Driver Class: org.h2.Driver
    JDBC URL: jdbc:h2:mem:testdb
    User Name: sa
    Password: <leave this empty>
----

TIP: The application is monitoring the table named: `SOME_TABLE`.

==== Application health endpoints

The following endpoints are exposed to assess application health:

* http://localhost:8080/health[_/health_] - 'OK'
* http://localhost:8080/version[_/version_] - current version of the application

=== Testing

Unit, Integration and end-to-end tests are provided.

NOTE: Please note that integration tests are using the **IT.java prefix and executed by the maven failsafe plugin

To run all except the end-to-end tests:
[indent=0]
----
	$ ./mvnw clean verify
----

==== End to end test

One front to back test is provided using htmlUnit. Since the execution of this test is relatively slow,
I decided to move this test to a separate maven profile.

In order to run all tests including the e2e test:
[indent=0]
----
	$ ./mvnw clean verify -Pe2e
----

=== Technology stack used by the application

The folowing technologies are  used by the application:

* Spring
* Spring Boot
* Spring integration
* Spring MVC
* Tomcat
* Slf4j - default spring boot configuration
* H2 database
* http://www.liquibase.org/[Liquibase] - to bootstrap db tables and triggers
* Spring webSocket support
* Mockito
* https://github.com/awaitility/awaitility[Awaitility] - for async waiting in tests
* https://projectlombok.org/[Lombok] - the reduce verbosity
* JQuery
* StompJs
* Twitter bootstrap - for advances layout
* HtmlUnit - for e2e testing

=== Technology considerations

* *Database:* I choose a lightweight H2 database to demonstrate the application, but the solution is mainly agnostic to database technology. (The sole H2 specific piece is the trigger definition but other databases support the same triggering concepts as well)
* *Spring integration:*  The database monitoring task can be considered as an integration problem (DB input -> Websocket Output) therefore I choose _Spring Integration_ that provides high level, resilient paradigms for system integration.
* *Messaging technology* I decided not to use any messaging (JMS) technology, since resiliency can be achieved on the database level and also coupling is low thank to Spring Integration.

=== Assumptions

I've made some main assumptions related to the requirements:

* The tool should monitor INSERT and UPDATE statements only.
* Only events (INSERT, UPDATE) occurred after the browser window opens appear on the screen. Previously created events do not.
* The tool has to be easily extendable to monitor more than one tables
* The tool monitoring mechanism should be (relatively) independent from the database technology.
* The table name to be monitored is hardcoded in the application (can easily be made dynamic by manually creating the DB triggers)
* The solution must be a development done: production ready implementation.


=== Design

Database Triggers are used (H2 in this case but can be generalised to other DB technologies) to detect and journal any table
updates or inserts. The trigger writes event records in a table called: *AUDIT_TRAIL_TABLE*. These audit trail records then picked
up and processed by the following _Spring Integration_ flow:

          +------------+    +------------+    +------------+    +------------+
H2        |  JDBC      |    |  Splitter  |    |Transformer |    | Websocket  |
AUDIT --->|  Inbound   |--->|            |--->|            |--->| Service    |-->BROWSER
TRAIL     |  Channel   |    |            |    |            |    | Activator  |
TABLE     |  Adapter   |    |            |    |            |    |            |
          +------------+    +------------+    +------------+    +------------+

Benefits of this design:

* Standard solution (EIP design patterns)
* Spring Integration provides resiliency and low coupling
* Highly customisable and modular
* Failover scenarios are provided by the framework (e.g Transaction rollback)


== License
Open Source software released under the
http://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].